import { DocSection } from './types';

/**
 * 示例文档数据
 * 用于测试和演示文档导航组件
 */
export const sampleDocSections: DocSection[] = [
  {
    id: 'getting-started',
    title: '快速开始',
    description: '了解如何快速开始使用我们的平台',
    path: '/docs/getting-started',
    icon: '🚀',
    order: 1,
    children: [
      {
        id: 'installation',
        title: '安装指南',
        slug: 'installation',
        path: '/docs/getting-started/installation',
        type: 'guide',
        order: 1,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['开发团队'],
          difficulty: 'beginner',
          estimatedTime: 10,
          tags: ['安装', '配置'],
        },
      },
      {
        id: 'quick-start',
        title: '快速入门',
        slug: 'quick-start',
        path: '/docs/getting-started/quick-start',
        type: 'tutorial',
        order: 2,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['开发团队'],
          difficulty: 'beginner',
          estimatedTime: 15,
          tags: ['入门', '教程'],
        },
      },
      {
        id: 'concepts',
        title: '基础概念',
        slug: 'concepts',
        path: '/docs/getting-started/concepts',
        type: 'guide',
        order: 3,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['开发团队'],
          difficulty: 'beginner',
          estimatedTime: 20,
          tags: ['概念', '基础'],
        },
      },
    ],
  },
  {
    id: 'api-reference',
    title: 'API 参考',
    description: '完整的 API 文档和参考资料',
    path: '/docs/api',
    icon: '📚',
    order: 2,
    children: [
      {
        id: 'api-overview',
        title: 'API 概览',
        slug: 'overview',
        path: '/docs/api/overview',
        type: 'api',
        order: 1,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['API 团队'],
          difficulty: 'intermediate',
          estimatedTime: 25,
          tags: ['API', '概览'],
        },
      },
      {
        id: 'authentication',
        title: '用户认证',
        slug: 'authentication',
        path: '/docs/api/auth',
        type: 'api',
        order: 2,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['API 团队'],
          difficulty: 'intermediate',
          estimatedTime: 30,
          tags: ['认证', 'JWT', '安全'],
        },
        children: [
          {
            id: 'login',
            title: '用户登录',
            slug: 'login',
            path: '/docs/api/auth/login',
            type: 'api',
            order: 1,
            metadata: {
              lastUpdated: new Date('2024-01-15'),
              contributors: ['API 团队'],
              difficulty: 'intermediate',
              estimatedTime: 15,
              tags: ['登录', 'API'],
            },
          },
          {
            id: 'register',
            title: '用户注册',
            slug: 'register',
            path: '/docs/api/auth/register',
            type: 'api',
            order: 2,
            metadata: {
              lastUpdated: new Date('2024-01-15'),
              contributors: ['API 团队'],
              difficulty: 'intermediate',
              estimatedTime: 15,
              tags: ['注册', 'API'],
            },
          },
        ],
      },
      {
        id: 'business-apis',
        title: '业务接口',
        slug: 'business',
        path: '/docs/api/business',
        type: 'api',
        order: 3,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['业务团队'],
          difficulty: 'advanced',
          estimatedTime: 45,
          tags: ['业务', '合伙人', '积分'],
        },
      },
    ],
  },
  {
    id: 'guides',
    title: '开发指南',
    description: '深入的开发指南和最佳实践',
    path: '/docs/guides',
    icon: '🛠️',
    order: 3,
    children: [
      {
        id: 'development',
        title: '开发规范',
        slug: 'development',
        path: '/docs/guides/development',
        type: 'guide',
        order: 1,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['开发团队'],
          difficulty: 'intermediate',
          estimatedTime: 35,
          tags: ['规范', '开发'],
        },
      },
      {
        id: 'architecture',
        title: '架构设计',
        slug: 'architecture',
        path: '/docs/guides/architecture',
        type: 'guide',
        order: 2,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['架构师'],
          difficulty: 'advanced',
          estimatedTime: 60,
          tags: ['架构', '设计'],
        },
      },
    ],
  },
  {
    id: 'examples',
    title: '示例和教程',
    description: '实际的代码示例和详细教程',
    path: '/docs/examples',
    icon: '💡',
    order: 4,
    children: [
      {
        id: 'code-examples',
        title: '代码示例',
        slug: 'code-examples',
        path: '/docs/examples/code',
        type: 'example',
        order: 1,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['开发团队'],
          difficulty: 'beginner',
          estimatedTime: 20,
          tags: ['示例', '代码'],
        },
      },
      {
        id: 'tutorials',
        title: '集成教程',
        slug: 'tutorials',
        path: '/docs/examples/tutorials',
        type: 'tutorial',
        order: 2,
        metadata: {
          lastUpdated: new Date('2024-01-15'),
          contributors: ['开发团队'],
          difficulty: 'intermediate',
          estimatedTime: 40,
          tags: ['教程', '集成'],
        },
      },
    ],
  },
];