import { SearchIndex } from './types';

/**
 * 示例搜索索引数据
 * 用于测试和演示搜索功能
 */
export const sampleSearchIndex: SearchIndex[] = [
  {
    id: 'getting-started',
    title: '快速开始',
    content: '欢迎使用 Optimus 平台！本指南将帮助您在 5 分钟内快速上手，了解平台的核心功能和使用方法。首先，您需要创建一个 Optimus 账号来访问我们的服务。登录后，您可以探索平台的各种功能模块，包括 API 服务、业务演示、文档中心等。',
    path: '/docs/getting-started',
    type: 'page',
    section: '快速开始',
    tags: ['入门', '教程', '基础'],
    lastUpdated: new Date('2024-01-15'),
    weight: 1.0,
  },
  {
    id: 'api-auth',
    title: '用户认证 API',
    content: 'Optimus 平台提供完整的用户认证 API，支持用户注册、登录、密码重置等功能。所有 API 都遵循 RESTful 设计规范，使用 JWT 令牌进行身份验证。登录接口 POST /client-user/login 需要提供用户名和密码，成功后返回访问令牌。',
    path: '/docs/api/auth',
    type: 'api',
    section: 'API 参考',
    tags: ['API', '认证', 'JWT', '登录', '注册'],
    lastUpdated: new Date('2024-01-15'),
    weight: 1.2,
  },
  {
    id: 'user-login-api',
    title: '用户登录接口',
    content: 'POST /client-user/login 用户登录接口，使用用户名和密码进行登录认证。请求参数包括 username（用户名或邮箱）和 password（密码）。成功响应返回 JWT 访问令牌和用户信息。失败时返回相应的错误码和错误信息。',
    path: '/docs/api/auth/login',
    type: 'api',
    section: 'API 参考',
    tags: ['API', '登录', 'POST', 'JWT'],
    lastUpdated: new Date('2024-01-15'),
    weight: 1.1,
  },
  {
    id: 'user-register-api',
    title: '用户注册接口',
    content: 'POST /client-user/register 用户注册接口，创建新的用户账号。需要提供用户名、邮箱地址和密码。用户名长度为 3-20 个字符，密码至少 6 个字符。注册成功后返回用户基本信息，包括用户 ID、用户名、邮箱等。',
    path: '/docs/api/auth/register',
    type: 'api',
    section: 'API 参考',
    tags: ['API', '注册', 'POST', '用户'],
    lastUpdated: new Date('2024-01-15'),
    weight: 1.1,
  },
  {
    id: 'partner-system',
    title: '合伙人系统',
    content: 'Optimus 平台提供完整的合伙人管理系统，支持多级合伙人体系、佣金计算、业绩统计等功能。合伙人可以通过推荐新用户获得佣金奖励，系统自动计算和分发佣金。管理员可以查看合伙人列表、设置佣金比例、管理合伙人等级。',
    path: '/docs/business/partner',
    type: 'page',
    section: '业务指南',
    tags: ['合伙人', '佣金', '推荐', '业务'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.9,
  },
  {
    id: 'javascript-example',
    title: 'JavaScript 集成示例',
    content: '本示例展示如何在 JavaScript 应用中集成 Optimus API。首先安装 axios 依赖，然后创建 API 客户端配置。示例包括用户登录、获取用户信息、调用业务接口等常见场景。所有示例都包含完整的错误处理和最佳实践。',
    path: '/docs/examples/javascript',
    type: 'example',
    section: '示例教程',
    tags: ['JavaScript', '示例', '集成', 'axios'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.8,
  },
  {
    id: 'python-sdk',
    title: 'Python SDK 使用指南',
    content: 'Optimus Python SDK 提供了简单易用的 Python 接口，封装了所有 API 调用。安装 SDK：pip install optimus-sdk。SDK 支持同步和异步调用，自动处理认证、重试、错误处理等。包含完整的类型提示和文档字符串。',
    path: '/docs/sdk/python',
    type: 'page',
    section: 'SDK 文档',
    tags: ['Python', 'SDK', 'pip', '异步'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.9,
  },
  {
    id: 'error-handling',
    title: '错误处理指南',
    content: 'Optimus API 使用标准的 HTTP 状态码和统一的错误响应格式。所有错误响应都包含错误码、错误消息和详细信息。常见错误包括：400 请求参数错误、401 未授权访问、403 权限不足、404 资源不存在、500 服务器内部错误。建议在客户端实现重试机制和用户友好的错误提示。',
    path: '/docs/guides/error-handling',
    type: 'page',
    section: '开发指南',
    tags: ['错误处理', 'HTTP', '状态码', '重试'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.8,
  },
  {
    id: 'rate-limiting',
    title: 'API 限流说明',
    content: 'Optimus API 实施了速率限制以确保服务稳定性。默认限制为每分钟 1000 次请求，每小时 10000 次请求。超出限制时返回 429 状态码。响应头包含限流信息：X-RateLimit-Limit（限制数量）、X-RateLimit-Remaining（剩余次数）、X-RateLimit-Reset（重置时间）。',
    path: '/docs/guides/rate-limiting',
    type: 'page',
    section: '开发指南',
    tags: ['限流', 'API', '429', '响应头'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.7,
  },
  {
    id: 'webhook-guide',
    title: 'Webhook 配置指南',
    content: 'Webhook 允许 Optimus 平台在特定事件发生时主动通知您的应用。支持的事件包括用户注册、订单创建、支付完成等。配置 Webhook 需要提供接收 URL 和签名密钥。所有 Webhook 请求都包含签名验证，确保请求来源的真实性。',
    path: '/docs/guides/webhooks',
    type: 'page',
    section: '开发指南',
    tags: ['Webhook', '事件', '通知', '签名'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.8,
  },
  {
    id: 'deployment-guide',
    title: '部署指南',
    content: '本指南介绍如何将使用 Optimus API 的应用部署到生产环境。包括环境变量配置、SSL 证书设置、负载均衡配置、监控和日志记录等。推荐使用 Docker 容器化部署，支持 Kubernetes 编排。提供了完整的 CI/CD 流水线示例。',
    path: '/docs/guides/deployment',
    type: 'page',
    section: '开发指南',
    tags: ['部署', 'Docker', 'Kubernetes', 'CI/CD'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.7,
  },
  {
    id: 'faq',
    title: '常见问题',
    content: '这里收集了用户在使用 Optimus 平台时经常遇到的问题和解决方案。包括账号注册问题、API 调用失败、认证错误、权限问题等。每个问题都提供了详细的解决步骤和相关文档链接。如果您的问题没有在这里找到答案，请联系技术支持。',
    path: '/docs/faq',
    type: 'page',
    section: '帮助中心',
    tags: ['FAQ', '问题', '解决方案', '支持'],
    lastUpdated: new Date('2024-01-15'),
    weight: 0.6,
  },
];