/**
 * 文章管理系统错误码映射
 * 与后端 ArticleHttpCode 保持一致
 */

// 文章相关错误 (40001-40099)
export const ARTICLE_ERRORS = {
  ARTICLE_NOT_FOUND: 40001,
  ARTICLE_ALREADY_EXISTS: 40002,
  ARTICLE_CREATE_FAILED: 40003,
  ARTICLE_UPDATE_FAILED: 40004,
  ARTICLE_DELETE_FAILED: 40005,
  ARTICLE_SLUG_ALREADY_EXISTS: 40006,
  ARTICLE_INVALID_STATUS: 40007,
  ARTICLE_CANNOT_PUBLISH: 40008,
  ARTICLE_CANNOT_ARCHIVE: 40009,
  ARTICLE_ALREADY_PUBLISHED: 40010,
  ARTICLE_ALREADY_ARCHIVED: 40011,
};

// 分类相关错误 (40101-40199)
export const CATEGORY_ERRORS = {
  CATEGORY_NOT_FOUND: 40101,
  CATEGORY_ALREADY_EXISTS: 40102,
  CATEGORY_CREATE_FAILED: 40103,
  CATEGORY_UPDATE_FAILED: 40104,
  CATEGORY_DELETE_FAILED: 40105,
  CATEGORY_HAS_ARTICLES: 40106,
  BUILT_IN_CATEGORY_CANNOT_DELETE: 40107,
  BUILT_IN_CATEGORY_CANNOT_UPDATE: 40108,
  CATEGORY_PARENT_NOT_FOUND: 40109,
  CATEGORY_CIRCULAR_REFERENCE: 40110,
  CATEGORY_CODE_ALREADY_EXISTS: 40111,
};

// 验证相关错误 (40201-40299)
export const VALIDATION_ERRORS = {
  COVER_IMAGES_EXCEED_LIMIT: 40201,
  INVALID_CATEGORY_CONFIG: 40202,
  INVALID_ARTICLE_TITLE: 40203,
  INVALID_ARTICLE_CONTENT: 40204,
  INVALID_ARTICLE_SUMMARY: 40205,
  INVALID_SLUG_FORMAT: 40206,
  INVALID_SORT_WEIGHT: 40207,
  INVALID_SEO_DATA: 40208,
  COVER_IMAGES_REQUIRED: 40209,
  INVALID_COVER_IMAGE_URL: 40210,
};

// 版本相关错误 (40301-40399)
export const VERSION_ERRORS = {
  VERSION_NOT_FOUND: 40301,
  VERSION_CREATE_FAILED: 40302,
  VERSION_DELETE_FAILED: 40303,
  VERSION_LIMIT_EXCEEDED: 40304,
  CANNOT_DELETE_PUBLISHED_VERSION: 40305,
  CANNOT_DELETE_CURRENT_VERSION: 40306,
  VERSION_ALREADY_CURRENT: 40307,
  VERSION_REVERT_FAILED: 40308,
  VERSION_COMPARE_FAILED: 40309,
  INVALID_VERSION_NUMBER: 40310,
  VERSION_ARTICLE_MISMATCH: 40311,
};

// 预定发布相关错误 (40401-40499)
export const SCHEDULED_ERRORS = {
  INVALID_SCHEDULED_TIME: 40401,
  SCHEDULED_TIME_IN_PAST: 40402,
  SCHEDULED_PUBLISH_FAILED: 40403,
  SCHEDULED_PUBLISH_CANCELLED: 40404,
  ARTICLE_NOT_SCHEDULED: 40405,
};

// 所有错误码
export const ERROR_CODES = {
  ...ARTICLE_ERRORS,
  ...CATEGORY_ERRORS,
  ...VALIDATION_ERRORS,
  ...VERSION_ERRORS,
  ...SCHEDULED_ERRORS,
};

// 错误消息映射（中文）
export const ERROR_MESSAGES = {
  // 文章相关错误
  [ARTICLE_ERRORS.ARTICLE_NOT_FOUND]: '文章不存在',
  [ARTICLE_ERRORS.ARTICLE_ALREADY_EXISTS]: '文章已存在',
  [ARTICLE_ERRORS.ARTICLE_CREATE_FAILED]: '文章创建失败',
  [ARTICLE_ERRORS.ARTICLE_UPDATE_FAILED]: '文章更新失败',
  [ARTICLE_ERRORS.ARTICLE_DELETE_FAILED]: '文章删除失败',
  [ARTICLE_ERRORS.ARTICLE_SLUG_ALREADY_EXISTS]: '文章标识符已存在',
  [ARTICLE_ERRORS.ARTICLE_INVALID_STATUS]: '无效的文章状态',
  [ARTICLE_ERRORS.ARTICLE_CANNOT_PUBLISH]: '文章无法发布',
  [ARTICLE_ERRORS.ARTICLE_CANNOT_ARCHIVE]: '文章无法归档',
  [ARTICLE_ERRORS.ARTICLE_ALREADY_PUBLISHED]: '文章已发布',
  [ARTICLE_ERRORS.ARTICLE_ALREADY_ARCHIVED]: '文章已归档',

  // 分类相关错误
  [CATEGORY_ERRORS.CATEGORY_NOT_FOUND]: '分类不存在',
  [CATEGORY_ERRORS.CATEGORY_ALREADY_EXISTS]: '分类已存在',
  [CATEGORY_ERRORS.CATEGORY_CREATE_FAILED]: '分类创建失败',
  [CATEGORY_ERRORS.CATEGORY_UPDATE_FAILED]: '分类更新失败',
  [CATEGORY_ERRORS.CATEGORY_DELETE_FAILED]: '分类删除失败',
  [CATEGORY_ERRORS.CATEGORY_HAS_ARTICLES]: '分类下存在文章，无法删除',
  [CATEGORY_ERRORS.BUILT_IN_CATEGORY_CANNOT_DELETE]: '内置分类不能删除',
  [CATEGORY_ERRORS.BUILT_IN_CATEGORY_CANNOT_UPDATE]: '内置分类不能修改',
  [CATEGORY_ERRORS.CATEGORY_PARENT_NOT_FOUND]: '父分类不存在',
  [CATEGORY_ERRORS.CATEGORY_CIRCULAR_REFERENCE]: '分类存在循环引用',
  [CATEGORY_ERRORS.CATEGORY_CODE_ALREADY_EXISTS]: '分类代码已存在',

  // 验证相关错误
  [VALIDATION_ERRORS.COVER_IMAGES_EXCEED_LIMIT]: '封面图片数量超出限制',
  [VALIDATION_ERRORS.INVALID_CATEGORY_CONFIG]: '无效的分类配置',
  [VALIDATION_ERRORS.INVALID_ARTICLE_TITLE]: '无效的文章标题',
  [VALIDATION_ERRORS.INVALID_ARTICLE_CONTENT]: '无效的文章内容',
  [VALIDATION_ERRORS.INVALID_ARTICLE_SUMMARY]: '无效的文章摘要',
  [VALIDATION_ERRORS.INVALID_SLUG_FORMAT]: '无效的标识符格式',
  [VALIDATION_ERRORS.INVALID_SORT_WEIGHT]: '无效的排序权重',
  [VALIDATION_ERRORS.INVALID_SEO_DATA]: '无效的SEO数据',
  [VALIDATION_ERRORS.COVER_IMAGES_REQUIRED]: '封面图片不能为空',
  [VALIDATION_ERRORS.INVALID_COVER_IMAGE_URL]: '无效的封面图片URL',

  // 版本相关错误
  [VERSION_ERRORS.VERSION_NOT_FOUND]: '版本不存在',
  [VERSION_ERRORS.VERSION_CREATE_FAILED]: '版本创建失败',
  [VERSION_ERRORS.VERSION_DELETE_FAILED]: '版本删除失败',
  [VERSION_ERRORS.VERSION_LIMIT_EXCEEDED]: '版本数量超出限制',
  [VERSION_ERRORS.CANNOT_DELETE_PUBLISHED_VERSION]: '不能删除已发布的版本',
  [VERSION_ERRORS.CANNOT_DELETE_CURRENT_VERSION]: '不能删除当前版本',
  [VERSION_ERRORS.VERSION_ALREADY_CURRENT]: '该版本已是当前版本',
  [VERSION_ERRORS.VERSION_REVERT_FAILED]: '版本回退失败',
  [VERSION_ERRORS.VERSION_COMPARE_FAILED]: '版本比较失败',
  [VERSION_ERRORS.INVALID_VERSION_NUMBER]: '无效的版本号',
  [VERSION_ERRORS.VERSION_ARTICLE_MISMATCH]: '版本与文章不匹配',

  // 预定发布相关错误
  [SCHEDULED_ERRORS.INVALID_SCHEDULED_TIME]: '无效的预定发布时间',
  [SCHEDULED_ERRORS.SCHEDULED_TIME_IN_PAST]: '预定发布时间不能早于当前时间',
  [SCHEDULED_ERRORS.SCHEDULED_PUBLISH_FAILED]: '预定发布失败',
  [SCHEDULED_ERRORS.SCHEDULED_PUBLISH_CANCELLED]: '预定发布已取消',
  [SCHEDULED_ERRORS.ARTICLE_NOT_SCHEDULED]: '文章未设置预定发布',
};
